/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package haxeunittests;

@:umodule("HaxeUnitTests")
@:glueCppIncludes("BasicTypesUObject.h")
@:uextern @:uclass extern class UBasicTypesUObject extends unreal.UObject {
  @:uproperty private var m_FStringProp : unreal.FString;
  @:uproperty public var doubleProp : unreal.Float64;
  @:uproperty public var floatProp : unreal.Float32;
  @:uproperty public var ui64Prop : unreal.FakeUInt64;
  @:uproperty public var i64Prop : unreal.Int64;
  @:uproperty public var ui32Prop : unreal.FakeUInt32;
  @:uproperty public var i32Prop : unreal.Int32;
  @:uproperty public var i16Prop : unreal.Int16;
  @:uproperty public var ui16Prop : unreal.UInt16;
  @:uproperty public var i8Prop : unreal.Int8;
  @:uproperty public var ui8Prop : unreal.UInt8;
  @:uproperty public var nameProp : unreal.FName;
  @:uproperty public var textProp : unreal.FText;
  @:uproperty public var stringProp : unreal.FString;
  @:uproperty public var boolProp : Bool;
  @:ufunction @:final public function getBoolProp() : Bool;
  @:ufunction @:final public function getStringProp() : unreal.FString;
  @:ufunction @:final public function getUi8Prop() : unreal.UInt8;
  @:ufunction @:final public function getI8Prop() : unreal.Int8;
  @:ufunction @:final public function getI32Prop() : unreal.Int32;
  @:ufunction @:final public function getUi32Prop() : unreal.FakeUInt32;
  @:ufunction @:final public function getI64Prop() : unreal.Int64;
  @:ufunction @:final public function getFloatProp() : unreal.Float32;
  @:ufunction @:final public function getDoubleProp() : unreal.Float64;
  @:ufunction @:final public function setBool_String_UI8_I8(b : Bool, str : unreal.FString, ui8 : unreal.UInt8, i8 : unreal.Int8) : haxeunittests.UBasicTypesUObject;
  @:ufunction public function setText(text : unreal.FText) : unreal.Int64;
  @:ufunction private function setBool_String_UI8_I8_protected(b : Bool, str : unreal.FString, ui8 : unreal.UInt8, i8 : unreal.Int8) : haxeunittests.UBasicTypesUObject;
  
}
