/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package cases;

@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("ObjectReflect.h")
@:uextern @:uclass extern class UObjectReflect extends unreal.UObject {
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeReflectStruct1.h")
@:uextern @:ustruct extern class FHaxeReflectStruct1 {
  @:uproperty public var ui32 : unreal.FakeUInt32;
  @:uproperty public var i32 : unreal.Int32;
  @:uproperty public var d1 : unreal.Float64;
  @:uproperty public var f1 : unreal.Float32;
  @:uproperty public var arr : unreal.TArray<unreal.FVector>;
  @:uproperty public var vec2d : unreal.FVector2D;
  @:uproperty public var vec : unreal.FVector;
  @:uproperty public var uobj : cases.TestUObjectOverrides.UHaxeDerived1;
  @:uproperty public var fname : unreal.FName;
  @:uproperty public var text : unreal.FText;
  @:uproperty public var str : unreal.FString;
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeReflectStruct2.h")
@:uextern @:ustruct extern class FHaxeReflectStruct2 {
  @:uproperty public var myCppEnum : haxeunittests.EMyCppEnum;
  @:uproperty public var myEnum : haxeunittests.EMyEnum;
  @:uproperty public var simple : cases.TestReflect.FHaxeReflectStruct1;
  
}
