/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package cases;

@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("StructTest.h")
@:uextern @:uclass extern class UStructTest extends unreal.UObject {
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeStruct.h")
@:uextern @:ustruct extern class FHaxeStruct {
  @:uproperty public var fname : unreal.FName;
  @:uproperty public var name : unreal.FString;
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("DerivedStruct.h")
@:uextern @:ustruct extern class FDerivedStruct extends haxeunittests.FPODStruct {
  @:uproperty public var addedProperty : cases.TestStructs.FHaxeStruct;
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeStruct2.h")
@:uextern @:ustruct extern class FHaxeStruct2 {
  @:uproperty public var embedded : cases.TestStructs.FHaxeStruct;
  
}
