/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package cases;

@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeTestActorReplication.h")
@:uextern @:uclass extern class AHaxeTestActorReplication extends unreal.AActor {
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeDerived0.h")
@:uextern @:uclass extern class UHaxeDerived0 extends haxeunittests.UBasicTypesSub1 implements haxeunittests.IBasicType2 {
  // BasicType2 interface implementation
  @:ufunction public function getSomeInt() : unreal.Int32;
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeDerived1.h")
@:uextern @:uclass extern class UHaxeDerived1 extends cases.TestUObjectOverrides.UHaxeDerived0 {
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeDerived2.h")
@:uextern @:uclass extern class UHaxeDerived2 extends cases.TestUObjectOverrides.UHaxeDerived1 {
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("HaxeDerived3.h")
@:uextern @:uclass extern class UHaxeDerived3 extends cases.TestUObjectOverrides.UHaxeDerived2 {
  @:ufunction public function exposedFunction(someActor : unreal.AActor) : Void;
  
}


@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("StaticOverride.h")
@:uextern @:uclass extern class UStaticOverride extends cases.TestStatic.UStaticClass {
  
}
