/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package cases;

@:glueCppIncludes("DelHaxe0.h")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe0 = unreal.DynamicMulticastDelegate<FDelHaxe0, Void->Void>;

/**
  @param arg0
  @param ReturnValue
  
**/
@:glueCppIncludes("DelHaxe1_RV.h")
@:uParamName("arg0")
@:uParamName("ReturnValue")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe1_RV = unreal.DynamicDelegate<FDelHaxe1_RV, unreal.Int32->unreal.Int32>;

/**
  @param arg0
  @param arg1
  
**/
@:glueCppIncludes("DelHaxe2.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe2 = unreal.DynamicMulticastDelegate<FDelHaxe2, unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  
**/
@:glueCppIncludes("DelHaxe3.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe3 = unreal.DynamicMulticastDelegate<FDelHaxe3, unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  
**/
@:glueCppIncludes("DelHaxe4.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe4 = unreal.DynamicMulticastDelegate<FDelHaxe4, unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  @param arg4
  
**/
@:glueCppIncludes("DelHaxe5.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:uParamName("arg4")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe5 = unreal.DynamicMulticastDelegate<FDelHaxe5, unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  @param arg4
  @param arg5
  
**/
@:glueCppIncludes("DelHaxe6.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:uParamName("arg4")
@:uParamName("arg5")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe6 = unreal.DynamicMulticastDelegate<FDelHaxe6, unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  @param arg4
  @param arg5
  @param arg6
  
**/
@:glueCppIncludes("DelHaxe7.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:uParamName("arg4")
@:uParamName("arg5")
@:uParamName("arg6")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe7 = unreal.DynamicMulticastDelegate<FDelHaxe7, unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  @param arg4
  @param arg5
  @param arg6
  @param arg7
  
**/
@:glueCppIncludes("DelHaxe8.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:uParamName("arg4")
@:uParamName("arg5")
@:uParamName("arg6")
@:uParamName("arg7")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxe8 = unreal.DynamicMulticastDelegate<FDelHaxe8, unreal.Int32->cases.TestDelegates.UUsesDelegate->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->unreal.Int32->Void>;

/**
  @param arg0
  
**/
@:glueCppIncludes("DelHaxeUFun3.h")
@:uParamName("arg0")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxeUFun3 = unreal.DynamicMulticastDelegate<FDelHaxeUFun3, unreal.PRef<haxeunittests.FSimpleUStruct>->Void>;

/**
  @param arg0
  @param ReturnValue
  
**/
@:glueCppIncludes("DelHaxeUFun3_RV.h")
@:uParamName("arg0")
@:uParamName("ReturnValue")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxeUFun3_RV = unreal.DynamicDelegate<FDelHaxeUFun3_RV, unreal.PRef<haxeunittests.FSimpleUStruct>->unreal.Int32>;

/**
  @param arg0
  
**/
@:glueCppIncludes("DelHaxeUFun4.h")
@:uParamName("arg0")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxeUFun4 = unreal.DynamicMulticastDelegate<FDelHaxeUFun4, unreal.Const<unreal.PRef<haxeunittests.FSimpleUStruct>>->Void>;

/**
  @param arg0
  @param ReturnValue
  
**/
@:glueCppIncludes("DelHaxeUFun4_RV.h")
@:uParamName("arg0")
@:uParamName("ReturnValue")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxeUFun4_RV = unreal.DynamicDelegate<FDelHaxeUFun4_RV, unreal.Const<unreal.PRef<haxeunittests.FSimpleUStruct>>->cases.TestDelegates.UUsesDelegate>;

/**
  @param arg0
  @param arg1
  @param arg2
  @param arg3
  @param ReturnValue
  
**/
@:glueCppIncludes("DelHaxeUFun5.h")
@:uParamName("arg0")
@:uParamName("arg1")
@:uParamName("arg2")
@:uParamName("arg3")
@:uParamName("ReturnValue")
@:umodule("HaxeUnitTests")
@:haxeGenerated
typedef FDelHaxeUFun5 = unreal.DynamicDelegate<FDelHaxeUFun5, unreal.Float32->unreal.Float64->unreal.Int32->unreal.FakeUInt32->haxeunittests.FSimpleUStruct>;

@:umodule("HaxeUnitTests")
@:haxeGenerated
@:glueCppIncludes("UsesDelegate.h")
@:uextern @:uclass extern class UUsesDelegate extends unreal.UObject {
  
}
