// Generated by Haxe
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
public class HaxeGlue : global::GlueModuleRules {
	
	public HaxeGlue(global::UnrealBuildTool.TargetInfo target) : base(target) {
		if (string.Equals(global::haxe.root.Sys.getEnv("DO_UNITY_BUILD"), null)) {
			global::UnrealBuildTool.BuildConfiguration.bUseUnityBuild = false;
		}
		
	}
	
	
}


